### ISSUE TITLE
Module '".contentlayer/data"' has no exported member '...'.ts(2305)

### ISSUE THREAD

**Issue by renomureza** [contentlayerdev/contentlayer#41]
Typescript displays error when I import `data` or `type` from `.contentlayer`: 

```javascript
// Module '".contentlayer/data"' has no exported member 'allJavascripts'.ts(2305)
import { allJavascripts } from ".contentlayer/data";
// Module '".contentlayer/types"' has no exported member 'Javascript'.ts(2305)
import { Javascript } from ".contentlayer/types";
```

While this still works well, I think it's quite annoying and error prone as there are no suggestions.

**Repo**: 
- https://github.com/renomureza/test-contentlayer-next
- https://github.com/renomureza/test-contentlayer-next/blob/main/pages/javascript/%5Bslug%5D.tsx#L1

**Screenshot:**

![image](https://user-images.githubusercontent.com/49445216/141441147-2f9ff736-4be6-47f2-993c-ee0ce0963b35.png)

**Comment by schickling** [comment]
Does it work after you [restarted the TS server in VSC?](https://stackoverflow.com/a/64456017)

**Comment by renomureza** [comment]
I have done it many times: 
1. delete node_module & contentlayer directory
2. reinstall all packages
3. restart VSCode

it doesn't solve the problem.

**Comment by laanayam333** [comment]
> Does it work after you [restarted the TS server in VSC?](https://stackoverflow.com/a/64456017)

I had the same issue and restarting the TS server solved it for me. 
1. With a .TS or .TSX file open, open the command palette with they keystroke CTRL+SHIFT+P.
2. Enter Typescript: Restart TS Server

**Comment by CarbonGhost** [comment]
If you haven't already, ensure that you build the content using
```
./node_modules/.bin/contentlayer build
```
then restart the TS server. This fixed the issue for me.

**Comment by renomureza** [comment]
@laanayam333  @CarbonGhost  can you test the repo i am using,

**Comment by CarbonGhost** [comment]
> ... can you test the repo i am using,

I didn't run into this error when I cloned your repository locally.

**Comment by ipatate** [comment]
corrected in #44 
```
yarn add contentlayer@dev next-contentlayer@dev
```

**Comment by renomureza** [comment]
@CarbonGhost Thanks for testing the repo I'm using.

I'm still having the same problem, I don't know if it's my editor problem or not.

I have switched to MDX Bundler.

I will close this issue.
