### ISSUE TITLE
Eslint Error: Unable to resolve path to module 'next-contentlayer'

### ISSUE THREAD

**Issue by chemicalkosek** [contentlayerdev/contentlayer#48]
Hi. I can't import anything from 'next-contentlayer':

```javascript
const { withContentlayer } = require('next-contentlayer');
```
```bash
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
ReferenceError: withContentLayer is not defined
```

The same for:
```javascript
import { useMDXComponent } from 'next-contentlayer/hooks';
```
Eslint shows:
```eslint
Unable to resolve path to module 'next-contentlayer/hooks'
```

Package.json:
```json
   "contentlayer": "0.0.32",
   "next-contentlayer": "0.0.32",
```

**Comment by schickling** [comment]
@chemicalkosek can you please share a link to the repository where I can reproduce this problem?

**Comment by chemicalkosek** [comment]
I'm trying to recreate it on a fresh project. Strangely everything is working.

On the affected project I tried removing `package-lock.json`, `node_modules`, `.next`. Reinstalling all packages. Nothing helps.
Feel free to close the issue if you definitely believe the problem lays somewhere else. Maybe I'll try to isolate it later.

**Comment by chemicalkosek** [comment]
Simply placing `.eslintrc` in the project will show you eslint errors in `next.config.js` and `pages/index.js`:
```
Unable to resolve path to module 'next-contentlayer'
```

I think I have recreated it here: https://github.com/chemicalkosek/contentlayertest

**Comment by schickling** [comment]
Thanks for providing this additional info @chemicalkosek and sorry for the delay.

I've just released a new `dev` version which hopefully addresses the problem you're facing. Could you please give it a try via `yarn add contentlayer@dev next-contentlayer@dev`? (Should install `0.0.34-dev.2`)

Also note that you have a little typo here:

![CleanShot 2021-12-02 at 11 52 29](https://user-images.githubusercontent.com/1567498/144408597-fb123c4c-9120-43fc-8bc7-b3cfd9cb6663.png)

**Comment by chemicalkosek** [comment]
Hey, it looks it fixed the one for next-contentlayer:
```
const { withContentlayer } = require('next-contentlayer');
```
but not for:
```
import { useMDXComponent } from 'next-contentlayer/hooks';
```
```
Unable to resolve path to module 'next-contentlayer/hooks'.
```
```
    "contentlayer": "0.0.34-dev.9",
    "next-contentlayer": "0.0.34-dev.9",
```

**Comment by schickling** [comment]
@chemicalkosek can you please update the reproduction repo with the new issue you're running into as it seems to work for me when giving it a try on your repro.

**Comment by schickling** [comment]
This should be fixed in the latest release: https://github.com/contentlayerdev/contentlayer/releases/tag/v0.0.34

**Comment by chemicalkosek** [comment]
Hi @schickling
I'm very sorry, I am piled up in work lately.
Anyway I have rechecked and indeed the issue is still there.
I have updated the repo: https://github.com/chemicalkosek/contentlayertest

It still fails at `pages/index.js` at this line:
```
import { useMDXComponent } from 'next-contentlayer/hooks';
```
```
Unable to resolve path to module 'next-contentlayer/hooks'.
```
Are you not experiencing the same behavior?

**Comment by schickling** [comment]
Sorry for the delay on this. I'll try to take a look at this soon!

**Comment by schickling** [comment]
@chemicalkosek just took a look into your project and it seems to work fine for me (with the latest version `0.2.1`). Can you please check whether the problem still exists for you?

<img width="1651" alt="image" src="https://user-images.githubusercontent.com/1567498/161137066-57757f54-7f7e-4a21-a3da-d8c06aa7213c.png">

**Comment by juanpmd** [comment]
> @chemicalkosek just took a look into your project and it seems to work fine for me (with the latest version `0.2.1`). Can you please check whether the problem still exists for you?
> 
> <img alt="image" width="1651" src="https://user-images.githubusercontent.com/1567498/161137066-57757f54-7f7e-4a21-a3da-d8c06aa7213c.png">

I am having the same issue, I follow the basic setup from the tutorial and it works perfectly but as soon as I write in `index.js` `import { useMDXComponent } from 'next-contentlayer/hooks'`, it throws me an error that says:

```
./node_modules/next-contentlayer/dist/hooks/jsx-runtime.cjs:1:0
Module not found: Package path ./jsx-runtime.js is not exported from package /pc_path/contentlayer-example/node_modules/react (see exports field in /pc_path/contentlayer-example/node_modules/react/package.json)

Import trace for requested module:
./node_modules/next-contentlayer/dist/hooks/useMDXComponent.js
./node_modules/next-contentlayer/dist/hooks/index.js
./pages/posts/[slug].js

https://nextjs.org/docs/messages/module-not-found
```

**Comment by chemicalkosek** [comment]
@juanpmd I think your issue is with react 18. Downgrading to 17 will fix it
@schickling I'm sorry, I'm drowning in work. Yes, I'm still having this issue. I see you're running the dev server. Can you try building it?

**Comment by schickling** [comment]
Now I think I understand what you're referring to @chemicalkosek - it's the following, right?

![CleanShot 2022-04-13 at 10 57 14](https://user-images.githubusercontent.com/1567498/163139824-847f7b19-452f-4f26-baa5-0a70680cde52.png)

This is actually not a problem in Contentlayer itself but [a bug in one of your used Eslint rules](https://github.com/import-js/eslint-plugin-import/issues/1810) (probably part of the `wesbos` eslint plugin). Nonetheless I acknowledge that until the author of the https://github.com/import-js/eslint-plugin-import has fixed this issue, this could be a common problem for Contentlayer users.

The easiest workaround for this problem right now is to add the following `eslint-disable-next-line` comment in front of that `import` statement:

```js
// TODO remove eslint-disable when fixed https://github.com/import-js/eslint-plugin-import/issues/1810
// eslint-disable-next-line import/no-unresolved
import { useMDXComponent } from 'next-contentlayer/hooks'

// ...
```

We'll also add this to our documentation as a known problem. (cc @seancdavis)

**Comment by krachtstefan** [comment]
Just a tip for everyone who has the same issue. You can create ignore rule in your `.eslintrc.json` to fix this issue for the entire project:

```
{
  "rules": {
    "import/no-unresolved": [
      2,
      {
        "ignore": [
          "contentlayer/generated",
          "next-contentlayer/hooks"
        ]
      }
    ]
  }
}
```

**Comment by slavakurilyak** [comment]
You can also use disable ESLint for `next.config.js`

For example:

```js
/* eslint @typescript-eslint/no-var-requires: "off" */

const { withContentlayer } = require('next-contentlayer')
```
